[project]
name = "async-ml-odyssey"
version = "0.1.0"
description = "Educational simulation of induction motors and ML evolution"
authors = "italian"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask",
]
